### PR TITLE
hopefully make it work again

### PR DESCRIPTION
**Pull request by ZaneHannanAU**
Use `userVisibleOnly: true` to have it hopefully work again.

### CODE REVIEW

**Comment by jrconlin** [comment]
First off, HUGE THANK YOU for looking into this. I'm currently swamped with other stuff so I've not had any bandwidth to look at this, so any help is more than welcome. (That and as you can see, my JS prowess is not great.)

Sigh. looks like there's more breakage because of changing APIs.

I've got a copy of the code running on one of my personal domains:
https://evilonastick.com/push (yes, I know, long story on that domain name, but it's got TLS)

Looks like `navigator.serviceWorker` no longer supports `add_listener`
```
TypeError: can't access property "addEventListener", navigator.serviceWorker is undefined push:685:1
```

I know it's possible to run this page off of localhost and bypass ServiceWorker needing to run off of a TLS machine (at least it was when I first built this). If you're even more generous with your time, you might be able to poke around that way.

Again, even this is a huge help. Thank You!

**Comment by ZaneHannanAU** [comment]
I'll look into it but nothing rn. Currently have 12hr long shifts for irl work haha...

**Comment by saschanaz** [comment]
Is this still valid? Is anything still broken?

**Comment by jrconlin** [comment]
I can't say because we never heard back. Closing this for now.

**Pull request closed without merging**
